version: 2
jobs:
  build:
    working_directory: ~/Dark-Bob/mro
    parallelism: 1
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      DISTUTILS_DEBUG: 1
    docker:
    - image: circleci/python:3.6.7
      environment:
        PGHOST: localhost
        PGUSER: ubuntu
    - image: circleci/postgres:9.6
      environment:
        POSTGRES_USER: ubuntu
        POSTGRES_DB: circle_test
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - run:
        name: Check python3 version
        command: python3 --version
    - run:
        name: Create venv
        command: |
          python3 -m venv ./test-venv
          source ./test-venv/bin/activate
          pip install -U pip
          pip install -U wheel
          pip install -r requirements.txt
          python3 setup.py install
    - run:
        name: Run Tests
        command: |
          source ./test-venv/bin/activate
          py.test
    # Save test results
    - store_test_results:
        path: /tmp/circleci-test-results
    # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results